### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kalpa61** [OceanSummerDay/HSTA_MER#1]
hi, thanks for your work. If I want to train on the CASME II dataset, which images of the dataset should I use? Each sample has a series of images from OnsetFrame to OffsetFrame. For each sample, Should I keep only OnsetFrame, ApexFrame, OffsetFrame images? I'm confused

**Comment by oceanhao** [comment]
Our model has two branches, one branch uses only OnsetFrame and ApexFrame, and the other branch uses the downsampling of the original series of images.
In the specific code implementation, https://github.com/OceanSummerDay/HSTA_MER/blob/main/hsta_model_core/casme3.py#L181
reads the entire series of images, and then
https://github.com/OceanSummerDay/HSTA_MER/blob/main/hsta_model_core/my_utils.py#L58
divides the data into the part that only uses OnsetFrame and ApexFrame and the downsampled part of the original series of images, and then inputs it to the model.
