### ISSUE TITLE
other_dataset

### ISSUE THREAD

**Issue by Yuuu008** [OceanSummerDay/HSTA_MER#2]
Thank you for sharing your work and providing the codebase! While reading through `datasets.py`, I noticed the following line:
```python
from other_dataset import other_VideoClsDataset
```
However, I couldn’t find the other_dataset.py file in the repository. Could you kindly  provide a reference version to help better understand and reproduce the code?

**Comment by ggvvo** [comment]
I have the same question. Did you get the file other_dataset.py? Did you try to email the author?

**Comment by oceanhao** [comment]
I apologize for this mistake. I will correct it after the paper is accepted. I am very upset that my work has not been accepted.
